### ISSUE TITLE
Mac Excel error - "Dictionary.cls is not supposed in VBE. The file can't be loaded."

### ISSUE THREAD

**Issue by sayem** [VBA-tools/VBA-Dictionary#12]
Hi, I'm new to VBA and I'm trying to load a macro on my Mac Excel that uses Scripting.Dictionary, and I'm trying to use VBA-Dictionary as a replacement for it, but I'm running into some errors. 

Importing the Dictionary.cls file throws an error saying that it's not supported in VBE and can't be loaded: 

![mac - dictionary cls error](https://cloud.githubusercontent.com/assets/327067/7999804/e5831200-0b06-11e5-95d1-3ebd540b64d7.png)

And I was trying to put it into a module and run it, but then that throws a compile error: 

![screen shot 2015-06-04 at 10 10 52 pm](https://cloud.githubusercontent.com/assets/327067/7999815/06a76cba-0b07-11e5-92eb-54d12b8ff089.png)

Any idea how I can load VBA-Dictionary? I'm on Excel for Mac 2011 (v14.5.1), would love any help.

**Comment by timhall** [comment]
Hi @sayem I have seen some line-ending encoding issues with downloading from Github, see this comment for resolution details: https://github.com/VBA-tools/VBA-Dictionary/issues/5#issuecomment-77081615

Let me know if that doesn't work for you.

**Comment by sayem** [comment]
Yup, simply downloading the entire repo and then importing did the trick. Thanks!
