### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by Shoelace** [VBA-tools/VBA-Dictionary#19]
i know the stated intent is for a drop-in replacement of Scripting.dictionary.

but i think there would be value in adding some "bonus features"
like sorted outputs..

ie. if there was a `Dict.sortedKeys` option i'm sure it would get used.

**Comment by Shoelace** [comment]
that may not be a goodexample.. but being able to go

    for x in Dict.sorted
        'do stuff
    next

where the values come in a sorted order would be extremely useful

**Comment by timhall** [comment]
Hi @Shoelace thanks for the suggestion, but I'm pretty firmly in the drop-in replacement camp and have some future work planned that strictly requires it (deciding at build time whether to include this library or a Scripting Runtime reference).

Additionally, I have had some trouble finding a straightforward, cross-platform sort method so if you come up with a reusable method, please feel free to post it here and I can revisit adding it or can add it as an example.
