### ISSUE TITLE
Support for Microsoft Office 2016 on MacOS

### ISSUE THREAD

**Issue by msluser** [VBA-tools/VBA-Dictionary#20]
Is this class expected to work on Microsoft Office 2016 on MacOS ?

Are there any special instructions to use VBA class files in this environment?

Thank you,

-Mark

**Comment by cladelpino** [comment]
@msluser  perhaps the answer by Alexander Poleschuk in this thread is relevant to your question, I haven't been able to test it yet: https://stackoverflow.com/questions/19869266/vba-excel-dictionary-on-mac

**Comment by timhall** [comment]
Tested this on the most recent Mac version and everything seems to be working normally, I think this was just a temporary issue while importing was disabled/removed from Mac 2016.
