### ISSUE TITLE
Default item function not working

### ISSUE THREAD

**Issue by abeyer99** [VBA-tools/VBA-Dictionary#22]
Hi, the default functionality for Scripting.Dictionary is the item function. But your dictionary does not do this for me. My key is a string and my item is a custom object. I am testing your dictionary on my Windows 10 machine. Excel 2016 version 1906. When I do dict.item(key), it works, though.

**Comment by timhall** [comment]
There is an attribute set for `Item` that should do this (`Attribute Item.VB_UserMemId = 0`), but attributes are only retained if you import `Dictionary.cls` into your project (i.e. copy-pasting code from Dictionary won't set the attribute). Try the following [Installation Instructions](https://github.com/VBA-tools/VBA-Dictionary#installing):

> Download the [latest release](https://github.com/VBA-tools/VBA-Dictionary/releases), unzip, and import Dictionary.cls into your VBA project.

If it's still not working after importing, please re-open this issue and let me know
