### ISSUE TITLE
Run-time error '424'    Object required

### ISSUE THREAD

**Issue by cosmoc** [VBA-tools/VBA-Dictionary#40]
Executing advanced example.  Run-time error '424'   Issue appears on

Dim Values As Variant
ReDim Values(Parsed("values").Count, 3)

from the advanced example 

The Spec.xlsx show all "pass"  

Running Windows Microsoft® Excel® for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20806) 64-bit

**Comment by DecimalTurn** [comment]
What is `Parsed` in this context?
Did you try to add a breakpoint and check its value using the Locals Window?

**Comment by cosmoc** [comment]
I am single-stepping in debug

I created an example.json using the same data as the first example in the Readme.md
I see this in the Watch Window.   
![image](https://github.com/VBA-tools/VBA-Dictionary/assets/5199225/4df27d05-dede-4d86-a467-15132d17c7c5)

**Comment by DecimalTurn** [comment]
Can you copy-paste the json content here?

Also, it looks like your question might belong in a different repo: https://github.com/VBA-tools/VBA-JSON

**Comment by cosmoc** [comment]
Oh - my error,    Yes - this is for VBA-JSON.  I obviously have too many tabs open at once.     Should I close this and repeat in VBA-JSON?

The JSON is the same as in the simple example
{"a":123,"b":[1,2,3,4],"c":{"d":456}}

**Comment by cosmoc** [comment]
Issue reported in the wrong repository.  My apologies.   Moving this report to VBA-JSON.

**Comment by DecimalTurn** [comment]
No worries, I've answered in the [new issue](https://github.com/VBA-tools/VBA-JSON/issues/260).
Feel free to close this one.
