### ISSUE TITLE
Does not distinguish between string and numeric keys.

### ISSUE THREAD

**Issue by JNurick** [VBA-tools/VBA-Dictionary#6]
Sub T1()
  Dim SD As Object
  Dim VD As Dictionary
  
  Set SD = CreateObject("Scripting.Dictionary")
  Set VD = New Dictionary
  
  SD.Add 1, "Numeral 1"
  SD.Add "1", "String 1"
  
  VD.Add 1, "Numeral 1"
  VD.Add "1", "String 1"  'Error 457
End Sub

**Comment by timhall** [comment]
Interesting! Thanks for bringing this up @JNurick, I'll add a test case and get this fixed shortly.
